### ISSUE TITLE
Trouver une problématique

### ISSUE THREAD

**Issue by Dillga** [Dillga/memoire_HT03#2]

**Comment by Dillga** [comment]
Pour avoir problématique relativement restreinte, je propose qu'on se concentre sur un aspect de l'innovation. J'entends par là que ça pourrait être sur l'histoire des lieux producteurs d'innovation, ou sur la façon dont une innovation se répand dans un milieu. T'en penses quoi ?

**Comment by Mathylde01** [comment]
Ou alors parler d'une époque spécifique

**Comment by Dillga** [comment]
On pourrait étudier les lieux de l'innovation et de voir comment ces lieux ont transformé la vision de l'innovation par la société et réciproquement
